# Colours
BLUE = (0, 184, 255)
BLACK = (255, 255, 255)
DARK_GREY = (42, 42, 42)
GREEN = (0, 255, 0)
ORANGE = (255, 90, 0)
RED = (180, 0, 0)
WHITE = (230, 230, 230)
YELLOW = (255, 210, 0)

# Screen
SCREEN_WIDTH = 920
SCREEN_HEIGHT = 1000
BORDER = 5

# Spaceship
SPACESHIP_WIDTH = 44
SPACESHIP_HEIGHT = 10
SPACESHIP_PATH = "static/img/spaceship.png"
LIVES = 3

# Walls
WALLS = 4
WALL_WIDTH = 24
WALL_HEIGHT = 22
WALL_PIX_SIZE = 4
# WALLS_COORDS = (
#     # Column 1
#     (SCREEN_WIDTH // 5.5 + 0 * WALL_PIX_SIZE, 4 + SCREEN_HEIGHT - 220),
#     (SCREEN_WIDTH // 5.5 + 0 * WALL_PIX_SIZE, 8 + SCREEN_HEIGHT - 220)
#     (SCREEN_WIDTH // 5.5 + 0 * WALL_PIX_SIZE, 12 + SCREEN_HEIGHT - 220)
#     (SCREEN_WIDTH // 5.5 + 0 * WALL_PIX_SIZE, 16 + SCREEN_HEIGHT - 220)
#     (SCREEN_WIDTH // 5.5 + 0 * WALL_PIX_SIZE, 20 + SCREEN_HEIGHT - 220)
#     (SCREEN_WIDTH // 5.5 + 0 * WALL_PIX_SIZE, 24 + SCREEN_HEIGHT - 220)
#     (SCREEN_WIDTH // 5.5 + 0 * WALL_PIX_SIZE, 28 + SCREEN_HEIGHT - 220)
#     (SCREEN_WIDTH // 5.5 + 0 * WALL_PIX_SIZE, 32 + SCREEN_HEIGHT - 220)
#     (SCREEN_WIDTH // 5.5 + 0 * WALL_PIX_SIZE, 36 + SCREEN_HEIGHT - 220)
#     (SCREEN_WIDTH // 5.5 + 0 * WALL_PIX_SIZE, 40 + SCREEN_HEIGHT - 220)
#     (SCREEN_WIDTH // 5.5 + 0 * WALL_PIX_SIZE, 44 + SCREEN_HEIGHT - 220)
#     (SCREEN_WIDTH // 5.5 + 0 * WALL_PIX_SIZE, 48 + SCREEN_HEIGHT - 220)
#     (SCREEN_WIDTH // 5.5 + 0 * WALL_PIX_SIZE, 52 + SCREEN_HEIGHT - 220)
#     (SCREEN_WIDTH // 5.5 + 0 * WALL_PIX_SIZE, 56 + SCREEN_HEIGHT - 220)
#     (SCREEN_WIDTH // 5.5 + 0 * WALL_PIX_SIZE, 60 + SCREEN_HEIGHT - 220)
#     (SCREEN_WIDTH // 5.5 + 0 * WALL_PIX_SIZE, 64 + SCREEN_HEIGHT - 220)
#     # Column 2
#     (SCREEN_WIDTH // 5.5 + 1 * WALL_PIX_SIZE, 0 + SCREEN_HEIGHT - 220)
#     (SCREEN_WIDTH // 5.5 + 1 * WALL_PIX_SIZE, 4 + SCREEN_HEIGHT - 220)
#     (SCREEN_WIDTH // 5.5 + 1 * WALL_PIX_SIZE, 8 + SCREEN_HEIGHT - 220)
#     (SCREEN_WIDTH // 5.5 + 1 * WALL_PIX_SIZE, 12 + SCREEN_HEIGHT - 220)
#     (SCREEN_WIDTH // 5.5 + 1 * WALL_PIX_SIZE, 16 + SCREEN_HEIGHT - 220)
#     (SCREEN_WIDTH // 5.5 + 1 * WALL_PIX_SIZE, 20 + SCREEN_HEIGHT - 220)
#     (SCREEN_WIDTH // 5.5 + 1 * WALL_PIX_SIZE, 24 + SCREEN_HEIGHT - 220)
#     (SCREEN_WIDTH // 5.5 + 1 * WALL_PIX_SIZE, 28 + SCREEN_HEIGHT - 220)
#     (SCREEN_WIDTH // 5.5 + 1 * WALL_PIX_SIZE, 32 + SCREEN_HEIGHT - 220)
#     (SCREEN_WIDTH // 5.5 + 1 * WALL_PIX_SIZE, 36 + SCREEN_HEIGHT - 220)
#     (SCREEN_WIDTH // 5.5 + 1 * WALL_PIX_SIZE, 40 + SCREEN_HEIGHT - 220)
#     (SCREEN_WIDTH // 5.5 + 1 * WALL_PIX_SIZE, 44 + SCREEN_HEIGHT - 220)
#     (SCREEN_WIDTH // 5.5 + 1 * WALL_PIX_SIZE, 48 + SCREEN_HEIGHT - 220)
#     (SCREEN_WIDTH // 5.5 + 1 * WALL_PIX_SIZE, 52 + SCREEN_HEIGHT - 220)
#     (SCREEN_WIDTH // 5.5 + 1 * WALL_PIX_SIZE, 56 + SCREEN_HEIGHT - 220)
#     (SCREEN_WIDTH // 5.5 + 1 * WALL_PIX_SIZE, 60 + SCREEN_HEIGHT - 220)
#     (SCREEN_WIDTH // 5.5 + 1 * WALL_PIX_SIZE, 64 + SCREEN_HEIGHT - 220)
#     # Column 3
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 2 * WALL_PIX_SIZE), -4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 2 * WALL_PIX_SIZE), 0 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 2 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 2 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 2 * WALL_PIX_SIZE), 12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 2 * WALL_PIX_SIZE), 16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 2 * WALL_PIX_SIZE), 20 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 2 * WALL_PIX_SIZE), 24 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 2 * WALL_PIX_SIZE), 28 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 2 * WALL_PIX_SIZE), 32 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 2 * WALL_PIX_SIZE), 36 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 2 * WALL_PIX_SIZE), 40 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 2 * WALL_PIX_SIZE), 44 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 2 * WALL_PIX_SIZE), 48 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 2 * WALL_PIX_SIZE), 52 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 2 * WALL_PIX_SIZE), 56 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 2 * WALL_PIX_SIZE), 60 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 2 * WALL_PIX_SIZE), 64 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     # Column 4
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 3 * WALL_PIX_SIZE), -8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 3 * WALL_PIX_SIZE), -4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 3 * WALL_PIX_SIZE), 0 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 3 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 3 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 3 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 3 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 3 * WALL_PIX_SIZE), 12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 3 * WALL_PIX_SIZE), 16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 3 * WALL_PIX_SIZE), 20 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 3 * WALL_PIX_SIZE), 24 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 3 * WALL_PIX_SIZE), 28 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 3 * WALL_PIX_SIZE), 32 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 3 * WALL_PIX_SIZE), 36 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 3 * WALL_PIX_SIZE), 40 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 3 * WALL_PIX_SIZE), 44 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 3 * WALL_PIX_SIZE), 48 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 3 * WALL_PIX_SIZE), 52 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 3 * WALL_PIX_SIZE), 56 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 3 * WALL_PIX_SIZE), 60 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 3 * WALL_PIX_SIZE), 64 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     # Column 5
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 4 * WALL_PIX_SIZE), -12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 4 * WALL_PIX_SIZE), -8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 4 * WALL_PIX_SIZE), -4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 4 * WALL_PIX_SIZE), 0 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 4 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 4 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 4 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 4 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 4 * WALL_PIX_SIZE), 12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 4 * WALL_PIX_SIZE), 16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 4 * WALL_PIX_SIZE), 20 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 4 * WALL_PIX_SIZE), 24 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 4 * WALL_PIX_SIZE), 28 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 4 * WALL_PIX_SIZE), 32 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 4 * WALL_PIX_SIZE), 36 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 4 * WALL_PIX_SIZE), 40 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 4 * WALL_PIX_SIZE), 44 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 4 * WALL_PIX_SIZE), 48 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 4 * WALL_PIX_SIZE), 52 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 4 * WALL_PIX_SIZE), 56 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 4 * WALL_PIX_SIZE), 60 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 4 * WALL_PIX_SIZE), 64 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     # Column 6
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 5 * WALL_PIX_SIZE), -16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 5 * WALL_PIX_SIZE), -12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 5 * WALL_PIX_SIZE), -8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 5 * WALL_PIX_SIZE), -4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 5 * WALL_PIX_SIZE), 0 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 5 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 5 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 5 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 5 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 5 * WALL_PIX_SIZE), 12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 5 * WALL_PIX_SIZE), 16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 5 * WALL_PIX_SIZE), 20 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 5 * WALL_PIX_SIZE), 24 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 5 * WALL_PIX_SIZE), 28 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 5 * WALL_PIX_SIZE), 32 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 5 * WALL_PIX_SIZE), 36 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 5 * WALL_PIX_SIZE), 40 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 5 * WALL_PIX_SIZE), 44 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 5 * WALL_PIX_SIZE), 48 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 5 * WALL_PIX_SIZE), 52 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 5 * WALL_PIX_SIZE), 56 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     # Column 7
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 6 * WALL_PIX_SIZE), -16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 6 * WALL_PIX_SIZE), -12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 6 * WALL_PIX_SIZE), -8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 6 * WALL_PIX_SIZE), -4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 6 * WALL_PIX_SIZE), 0 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 6 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 6 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 6 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 6 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 6 * WALL_PIX_SIZE), 12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 6 * WALL_PIX_SIZE), 16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 6 * WALL_PIX_SIZE), 20 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 6 * WALL_PIX_SIZE), 24 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 6 * WALL_PIX_SIZE), 28 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 6 * WALL_PIX_SIZE), 32 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 6 * WALL_PIX_SIZE), 36 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 6 * WALL_PIX_SIZE), 40 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 6 * WALL_PIX_SIZE), 44 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 6 * WALL_PIX_SIZE), 48 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 6 * WALL_PIX_SIZE), 52 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     # Column 8
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 7 * WALL_PIX_SIZE), -16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 7 * WALL_PIX_SIZE), -12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 7 * WALL_PIX_SIZE), -8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 7 * WALL_PIX_SIZE), -4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 7 * WALL_PIX_SIZE), 0 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 7 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 7 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 7 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 7 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 7 * WALL_PIX_SIZE), 12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 7 * WALL_PIX_SIZE), 16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 7 * WALL_PIX_SIZE), 20 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 7 * WALL_PIX_SIZE), 24 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 7 * WALL_PIX_SIZE), 28 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 7 * WALL_PIX_SIZE), 32 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 7 * WALL_PIX_SIZE), 36 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 7 * WALL_PIX_SIZE), 40 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 7 * WALL_PIX_SIZE), 44 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 7 * WALL_PIX_SIZE), 48 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     # Column 9
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 8 * WALL_PIX_SIZE), -16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 8 * WALL_PIX_SIZE), -12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 8 * WALL_PIX_SIZE), -8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 8 * WALL_PIX_SIZE), -4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 8 * WALL_PIX_SIZE), 0 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 8 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 8 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 8 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 8 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 8 * WALL_PIX_SIZE), 12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 8 * WALL_PIX_SIZE), 16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 8 * WALL_PIX_SIZE), 20 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 8 * WALL_PIX_SIZE), 24 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 8 * WALL_PIX_SIZE), 28 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 8 * WALL_PIX_SIZE), 32 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 8 * WALL_PIX_SIZE), 36 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 8 * WALL_PIX_SIZE), 40 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 8 * WALL_PIX_SIZE), 44 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     # Column 10
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 9 * WALL_PIX_SIZE), -16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 9 * WALL_PIX_SIZE), -12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 9 * WALL_PIX_SIZE), -8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 9 * WALL_PIX_SIZE), -4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 9 * WALL_PIX_SIZE), 0 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 9 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 9 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 9 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 9 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 9 * WALL_PIX_SIZE), 12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 9 * WALL_PIX_SIZE), 16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 9 * WALL_PIX_SIZE), 20 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 9 * WALL_PIX_SIZE), 24 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 9 * WALL_PIX_SIZE), 28 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 9 * WALL_PIX_SIZE), 32 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 9 * WALL_PIX_SIZE), 36 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 9 * WALL_PIX_SIZE), 40 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 9 * WALL_PIX_SIZE), 44 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     # Column 11
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 10 * WALL_PIX_SIZE), -16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 10 * WALL_PIX_SIZE), -12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 10 * WALL_PIX_SIZE), -8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 10 * WALL_PIX_SIZE), -4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 10 * WALL_PIX_SIZE), 0 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 10 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 10 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 10 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 10 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 10 * WALL_PIX_SIZE), 12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 10 * WALL_PIX_SIZE), 16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 10 * WALL_PIX_SIZE), 20 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 10 * WALL_PIX_SIZE), 24 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 10 * WALL_PIX_SIZE), 28 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 10 * WALL_PIX_SIZE), 32 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 10 * WALL_PIX_SIZE), 36 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 10 * WALL_PIX_SIZE), 40 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 10 * WALL_PIX_SIZE), 44 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     # Column 12
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 11 * WALL_PIX_SIZE), -16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 11 * WALL_PIX_SIZE), -12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 11 * WALL_PIX_SIZE), -8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 11 * WALL_PIX_SIZE), -4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 11 * WALL_PIX_SIZE), 0 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 11 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 11 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 11 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 11 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 11 * WALL_PIX_SIZE), 12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 11 * WALL_PIX_SIZE), 16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 11 * WALL_PIX_SIZE), 20 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 11 * WALL_PIX_SIZE), 24 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 11 * WALL_PIX_SIZE), 28 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 11 * WALL_PIX_SIZE), 32 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 11 * WALL_PIX_SIZE), 36 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 11 * WALL_PIX_SIZE), 40 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 11 * WALL_PIX_SIZE), 44 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     # Column 13
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 12 * WALL_PIX_SIZE), -16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 12 * WALL_PIX_SIZE), -12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 12 * WALL_PIX_SIZE), -8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 12 * WALL_PIX_SIZE), -4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 12 * WALL_PIX_SIZE), 0 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 12 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 12 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 12 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 12 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 12 * WALL_PIX_SIZE), 12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 12 * WALL_PIX_SIZE), 16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 12 * WALL_PIX_SIZE), 20 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 12 * WALL_PIX_SIZE), 24 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 12 * WALL_PIX_SIZE), 28 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 12 * WALL_PIX_SIZE), 32 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 12 * WALL_PIX_SIZE), 36 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 12 * WALL_PIX_SIZE), 40 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 12 * WALL_PIX_SIZE), 44 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     # Column 14
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 13 * WALL_PIX_SIZE), -16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 13 * WALL_PIX_SIZE), -12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 13 * WALL_PIX_SIZE), -8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 13 * WALL_PIX_SIZE), -4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 13 * WALL_PIX_SIZE), 0 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 13 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 13 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 13 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 13 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 13 * WALL_PIX_SIZE), 12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 13 * WALL_PIX_SIZE), 16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 13 * WALL_PIX_SIZE), 20 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 13 * WALL_PIX_SIZE), 24 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 13 * WALL_PIX_SIZE), 28 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 13 * WALL_PIX_SIZE), 32 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 13 * WALL_PIX_SIZE), 36 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 13 * WALL_PIX_SIZE), 40 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 13 * WALL_PIX_SIZE), 44 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     # Column 15
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 14 * WALL_PIX_SIZE), -16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 14 * WALL_PIX_SIZE), -12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 14 * WALL_PIX_SIZE), -8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 14 * WALL_PIX_SIZE), -4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 14 * WALL_PIX_SIZE), 0 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 14 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 14 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 14 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 14 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 14 * WALL_PIX_SIZE), 12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 14 * WALL_PIX_SIZE), 16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 14 * WALL_PIX_SIZE), 20 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 14 * WALL_PIX_SIZE), 24 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 14 * WALL_PIX_SIZE), 28 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 14 * WALL_PIX_SIZE), 32 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 14 * WALL_PIX_SIZE), 36 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 14 * WALL_PIX_SIZE), 40 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 14 * WALL_PIX_SIZE), 44 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     # Column 16
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 15 * WALL_PIX_SIZE), -16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 15 * WALL_PIX_SIZE), -12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 15 * WALL_PIX_SIZE), -8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 15 * WALL_PIX_SIZE), -4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 15 * WALL_PIX_SIZE), 0 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 15 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 15 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 15 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 15 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 15 * WALL_PIX_SIZE), 12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 15 * WALL_PIX_SIZE), 16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 15 * WALL_PIX_SIZE), 20 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 15 * WALL_PIX_SIZE), 24 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 15 * WALL_PIX_SIZE), 28 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 15 * WALL_PIX_SIZE), 32 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 15 * WALL_PIX_SIZE), 36 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 15 * WALL_PIX_SIZE), 40 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 15 * WALL_PIX_SIZE), 44 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 15 * WALL_PIX_SIZE), 48 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     # Column 17
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 16 * WALL_PIX_SIZE), -16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 16 * WALL_PIX_SIZE), -12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 16 * WALL_PIX_SIZE), -8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 16 * WALL_PIX_SIZE), -4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 16 * WALL_PIX_SIZE), 0 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 16 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 16 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 16 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 16 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 16 * WALL_PIX_SIZE), 12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 16 * WALL_PIX_SIZE), 16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 16 * WALL_PIX_SIZE), 20 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 16 * WALL_PIX_SIZE), 24 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 16 * WALL_PIX_SIZE), 28 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 16 * WALL_PIX_SIZE), 32 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 16 * WALL_PIX_SIZE), 36 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 16 * WALL_PIX_SIZE), 40 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 16 * WALL_PIX_SIZE), 44 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 16 * WALL_PIX_SIZE), 48 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 16 * WALL_PIX_SIZE), 52 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     # Column 18
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 17 * WALL_PIX_SIZE), -16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 17 * WALL_PIX_SIZE), -12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 17 * WALL_PIX_SIZE), -8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 17 * WALL_PIX_SIZE), -4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 17 * WALL_PIX_SIZE), 0 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 17 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 17 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 17 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 17 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 17 * WALL_PIX_SIZE), 12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 17 * WALL_PIX_SIZE), 16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 17 * WALL_PIX_SIZE), 20 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 17 * WALL_PIX_SIZE), 24 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 17 * WALL_PIX_SIZE), 28 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 17 * WALL_PIX_SIZE), 32 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 17 * WALL_PIX_SIZE), 36 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 17 * WALL_PIX_SIZE), 40 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 17 * WALL_PIX_SIZE), 44 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 17 * WALL_PIX_SIZE), 48 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 17 * WALL_PIX_SIZE), 52 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 17 * WALL_PIX_SIZE), 56 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     # Column 19
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 18 * WALL_PIX_SIZE), -12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 18 * WALL_PIX_SIZE), -8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 18 * WALL_PIX_SIZE), -4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 18 * WALL_PIX_SIZE), 0 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 18 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 18 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 18 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 18 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 18 * WALL_PIX_SIZE), 12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 18 * WALL_PIX_SIZE), 16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 18 * WALL_PIX_SIZE), 20 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 18 * WALL_PIX_SIZE), 24 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 18 * WALL_PIX_SIZE), 28 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 18 * WALL_PIX_SIZE), 32 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 18 * WALL_PIX_SIZE), 36 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 18 * WALL_PIX_SIZE), 40 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 18 * WALL_PIX_SIZE), 44 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 18 * WALL_PIX_SIZE), 48 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 18 * WALL_PIX_SIZE), 52 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 18 * WALL_PIX_SIZE), 56 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 18 * WALL_PIX_SIZE), 60 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 18 * WALL_PIX_SIZE), 64 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     # Column 20
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 19 * WALL_PIX_SIZE), -8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 19 * WALL_PIX_SIZE), -4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 19 * WALL_PIX_SIZE), 0 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 19 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 19 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 19 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 19 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 19 * WALL_PIX_SIZE), 12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 19 * WALL_PIX_SIZE), 16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 19 * WALL_PIX_SIZE), 20 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 19 * WALL_PIX_SIZE), 24 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 19 * WALL_PIX_SIZE), 28 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 19 * WALL_PIX_SIZE), 32 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 19 * WALL_PIX_SIZE), 36 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 19 * WALL_PIX_SIZE), 40 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 19 * WALL_PIX_SIZE), 44 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 19 * WALL_PIX_SIZE), 48 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 19 * WALL_PIX_SIZE), 52 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 19 * WALL_PIX_SIZE), 56 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 19 * WALL_PIX_SIZE), 60 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 19 * WALL_PIX_SIZE), 64 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     # Column 21
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 20 * WALL_PIX_SIZE), -4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 20 * WALL_PIX_SIZE), 0 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 20 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 20 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 20 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 20 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 20 * WALL_PIX_SIZE), 12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 20 * WALL_PIX_SIZE), 16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 20 * WALL_PIX_SIZE), 20 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 20 * WALL_PIX_SIZE), 24 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 20 * WALL_PIX_SIZE), 28 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 20 * WALL_PIX_SIZE), 32 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 20 * WALL_PIX_SIZE), 36 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 20 * WALL_PIX_SIZE), 40 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 20 * WALL_PIX_SIZE), 44 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 20 * WALL_PIX_SIZE), 48 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 20 * WALL_PIX_SIZE), 52 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 20 * WALL_PIX_SIZE), 56 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 20 * WALL_PIX_SIZE), 60 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 20 * WALL_PIX_SIZE), 64 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     # Column 22
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 21 * WALL_PIX_SIZE), 0 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 21 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 21 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 21 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 21 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 21 * WALL_PIX_SIZE), 12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 21 * WALL_PIX_SIZE), 16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 21 * WALL_PIX_SIZE), 20 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 21 * WALL_PIX_SIZE), 24 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 21 * WALL_PIX_SIZE), 28 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 21 * WALL_PIX_SIZE), 32 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 21 * WALL_PIX_SIZE), 36 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 21 * WALL_PIX_SIZE), 40 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 21 * WALL_PIX_SIZE), 44 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 21 * WALL_PIX_SIZE), 48 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 21 * WALL_PIX_SIZE), 52 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 21 * WALL_PIX_SIZE), 56 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 21 * WALL_PIX_SIZE), 60 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 21 * WALL_PIX_SIZE), 64 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     # Column 23
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 22 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 22 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 22 * WALL_PIX_SIZE), 4 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 22 * WALL_PIX_SIZE), 8 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 22 * WALL_PIX_SIZE), 12 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 22 * WALL_PIX_SIZE), 16 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 22 * WALL_PIX_SIZE), 20 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 22 * WALL_PIX_SIZE), 24 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 22 * WALL_PIX_SIZE), 28 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 22 * WALL_PIX_SIZE), 32 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 22 * WALL_PIX_SIZE), 36 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 22 * WALL_PIX_SIZE), 40 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 22 * WALL_PIX_SIZE), 44 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 22 * WALL_PIX_SIZE), 48 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 22 * WALL_PIX_SIZE), 52 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 22 * WALL_PIX_SIZE), 56 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 22 * WALL_PIX_SIZE), 60 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
#     wall_piece = Wall((SCREEN_WIDTH // 5.5 + 22 * WALL_PIX_SIZE), 64 + SCREEN_HEIGHT - 220)
#     wall_group.add(wall_piece)
# )

# Aliens
COLUMNS = 11
ROWS = 6
ALIEN_HEIGHT = 32
ALIEN_WIDTH = 48
ALIEN_SHOT_PATH = "static/img/alien_shot.gif"
POINTS_10 = ("static/img/10_points_1.png", "static/img/10_points_2.png")
POINTS_20 = ("static/img/20_points_1.png", "static/img/20_points_2.png")
POINTS_30 = ("static/img/30_points_1.png", "static/img/30_points_2.png")
POINTS_100 = "static/img/30_points_1.png"
ALIEN_EXPLOSION = "static/img/alien_explosion.png"
MOVEMENT_DELAY = 0.25
ALIEN_MOVEMENT = 10
MOVEMENTS_NUM = 4
ALIEN_SHOOT_DELAY = 1
ALIEN_SHOT_SPEED = 5
# alien destruction time in milliseconds
DESTRUCTION_TIME = 250

# Shot
SHOT_SPEED = 10
# Shot delay in seconds
SHOT_DELAY = 0.5

# Collision sounds
HIT_SOUND_1 = "static/sound/hit1.mp3"
HIT_SOUND_2 = "static/sound/hit2.mp3"

# HUD line height
GREEN_LINE_HEIGHT = 2

